---
- name: Charger les données des VMs
  include_vars:
    file: "{{ role_path }}/files/vms_data.yml"

- name: Création des VMs sur Proxmox
  vars:
    ansible_python_interpreter: /usr/bin/python3
  community.general.proxmox_kvm:
    api_host: "192.168.1.45"
    api_user: "root@pam"
    api_password: "M@lcolm44*"
    node: "pve_alex"
    vmid: "{{ item.vmid }}"
    name: "{{ item.name }}"
    memory: "{{ item.memory }}"
    cores: "{{ item.cores }}"
    sockets: "{{ item.sockets }}"
    sata:
      sata0: 'VMs_LVM:10,format=raw'
    storage: "{{ item.storage }}"
    net:
      net0: "virtio,bridge=vmbr0"
    ide:
      ide2: "local:iso/ubuntu-24.04-live-server-amd64,media=cdrom"
    state: "present"
  loop: "{{ vms }}"